repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        additional_dependencies:
          - black==23.9.1

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - django==5.2.6

  - repo: local
    hooks:
      - id: pylint
        name: pylint (accounts)
        entry: pylint accounts booking_mvp users
        language: python
        additional_dependencies:
          - pylint==3.2.5
          - django==5.2.6
