[tool.ruff]
target-version = "py311" 
exclude = ["**/migrations/**", "**/tests/**"]

[tool.ruff.lint]
select = ["E", "F", "B", "UP", "I"] 
ignore = ["E501"] 
extend-select = ["D"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_unused_configs = true
no_implicit_optional = false
exclude = "src/__init__.py"
